### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lichaoaaron** [Amanda-Zheng/MR-GNAS#1]
Hi, I got this error
"from configs.genotypes import Genotype
ModuleNotFoundError: No module named 'configs'"

So the 'configs' directory is missing.

**Comment by Amanda-Zheng** [comment]
The configs directory has been added. Thanks for pointing this out.

**Comment by lichaoaaron** [comment]
Thank you for solving this problem!
I got another error of "No module named 'utils.gpu_memory_log'"
You could download the code and try to run it and all the errors could be fixed.
